Upgrade MapFish to version 2.2.1
Version 2.2.1 uses pdfbox 3.0.3 the same as in GeoNetwork. The version 2.2.0 used pdfbox 2.0.x and was causing the following error when creating a thumbnail from a WMS service in the metadata editor, due to API changes in pdfbox:

Caused by: java.lang.NoSuchMethodError: 'org.apache.pdfbox.pdmodel.PDDocument org.apache.pdfbox.pdmodel.PDDocument.load(java.io.File)'
    at org.mapfish.print.output.FileCachingJaiMosaicOutputFactory.createImages(FileCachingJaiMosaicOutputFactory.java:143)
    at org.mapfish.print.output.FileCachingJaiMosaicOutputFactory.print(FileCachingJaiMosaicOutputFactory.java:89)
    at org.fao.geonet.kernel.thumbnail.ThumbnailMaker.generateThumbnail(ThumbnailMaker.java:169)
    at org.fao.geonet.api.records.attachments.AttachmentsActionsApi.saveThumbnail(AttachmentsActionsApi.java:131)