Link analysis improvement (#4607)
* Link analysis improvement

* API GET /records/links
  * Filter by groupOwner(s) or groupPublished(s)
  * Allow to editorOrMore profile
  * Filter on user editing groups by default
* API POST /records/links
  * Return a report based on user privileges

* Link analysis / Add CSV export.

* Link analysis / Add CSV export / Properties for test.

* Link analysis / Add CSV export / Properties for test.

* Link analysis / Do not set default values for group. By default all.

* Link analysis / Fix download link.

* Java / Autowired.

* Link analysis / Fix error on Tomact


Due to JSON parameter.

```
24-Apr-2020 14:05:38.281 INFO [http-apr-8080-exec-11] org.apache.coyote.http11.AbstractHttp11Processor.process Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
    at org.apache.coyote.http11.InternalAprInputBuffer.parseRequestLine(InternalAprInputBuffer.java:244)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1065)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
    at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2464)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
```

* Update AccessManager.java