Add timezone support (#5061)
* Remove Joda time library and use standard Java 8 java.time classes.

Part of https://github.com/geonetwork/core-geonetwork/issues/1970 (#1970).

* Remove Joda time and legacy java.util.Date and Calendar uses

* Fix failing tests

* Clean old commented code

* Refactor formatter as constant field

* Test / Fix

Force entity to be saved.

```
[ERROR] Failures:
[ERROR]   GeonetRepositoryTest.testBatchUpdateAttributes:125 expected:<[Updated DataElem]> but was:<[<md>metadata12</md>]>
[ERROR]   MetadataRepositoryTest.testIncrementPopularity:95 expected:<33> but was:<32>
```

We don't really know why this is required and how it is linked to the Joda removal.

* Date / UI / Add timezone configuration.

Use:
* `Browser` to use browser timezone
* otherwise define a specific timezone to use to display date eg.
`Australia/Hobart`

Add:
* Timezone directive / now support search by offset
* Timezone directive / display more values

* Date / UI / Editor / Add timezone basic support.

* Test / XSL in core tests had dependencies on services.

* Test / Tentative fix

Test working locally but not on travis:
```
[ERROR] UrlAnalyzerTest.urlCheckerToSetStatus:250 expected:<12> but was:<6>
```

* Popularity / Use updater instead of  which does not need flush. Fix index field name for popularity.

* Use UTC when possible

* Remove Joda time references

* Fix parsing string case with one or two milliseconds digits

* Add missing code moved removed from MetadataUtils

Add code removed from MetadataUtils to XslUtils
See commit a5a6cd79b8005472db7d7f8a7a3c26779fc686ea

* Fix gnDatePicker time check to select the timezone

* Fix Link Status date time format

* Fix exception in harvesters when calculating current date

* Interpret dates in format yyyy-mm-dd as local datetime

* Fix test for time and offset without date

* Use UTC to store date/times in the database

* Use the instant in equals method

Instead of considering that two ISODate objects are equals when they have
the same hour, minute and second compare the instant of both ISODate.

* Use UTC in MetadataStatus' changedate column

* Set the default timezone

Use the system/server/timezone setting to set the system's default timezone.
If the setting is blank or not present in the database fallback to the original
timezone of the JVM (server timezone, Java parameter user.timezone, environment
 variable TZ...)

* Refactor ISODate and create a new DateUtils class

Extract the static functionality of ISODate to an DateUtils utility class
in common project.

* Trim string to parse

* Use Zulu time to index metadata

Interpret the dates/ date-times appearing in the XML document as the timezone
set in the settings if the string hasn't a explicit time offset.

* Timezone support / SQL / Add migration.

* Migrate existing date time columns to UTC timezone

This commit adds a migration of the DateTime zones from the zone defined in
system timezone setting to UTC in case the date in the database doesn't have a
explicit timezone.

* Fix Source uuid type mapping

* Print the date in new metadata using server timezone setting

Changes the behaviour introduced in #5144 [1] and uses the timezone setting
to print the date/time in new created metadata adding the timezone
to the date. For example "2020-12-17T03:58:29.074-05:00[America/Toronto]".

[1] https://github.com/geonetwork/core-geonetwork/pull/5144

* Migration / In case we can't parse existing dates, assign now.

* Migration / Keep this as an example. But timezone migration is handled by Java task.

* Timezone config and translations.

* Workflow / Add missing field required for search results.

* CSW / GetDomain operation not implemented in ES.

* History / Do not fail on unknown user (which should not happen).

* Serialize dateAndTime property to JSON

Co-authored-by: Francois Prunayre <fx.prunayre@gmail.com>
Co-authored-by: Jose García <josegar74@gmail.com>