Add missing bootstrap-datepicker3.css.map that caused a wro4j error. (#8078)
ERROR [geonetwork.wro4j] - Error occurred during a wro4j request handling
ro.isdc.wro.WroRuntimeException: Cannot build valid CacheKey from request: /geonetwork/static/bootstrap-datepicker3.css.map