Record view / PDF / No CSS applied
The error comes from FOP loading CSS with path containing ".."
and getting errors from Spring (due to update done in v4)

```
[WARNING] /geonetwork/srv/fre/../../static/gn_metadata_pdf.css
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
    at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest (StrictHttpFirewall.java:340)
 
```

Use baseUrl instead to avoid that error.