Exclude log4j2 dependencies from MapFish.
The dependency adds some additional dependencies, causing this type of errors:
  java.lang.NoSuchMethodError: org.apache.logging.log4j.util.StackLocatorUtil.getCallerClassLoader(I)Ljava/lang/ClassLoader;