Add service associated resource. Fix add link from service distribution section. (#8958)
* Add service associated resource. Fix add link from service distribution section.

The online resource added to the dataset contained the text 'undefined' instead of the service online resource name

* Editor / Add service / When selecting layers, button was inactive

The link added to the dataset should contains the list of layers selected. Exception was swallowed 

```
TypeError: Cannot read properties of undefined (reading 'addLayerNamesMode')
    at setLayersParams (OnlineSrcService.js:141:35)
    at setParams (OnlineSrcService.js:112:16)
    at Object.linkToService (OnlineSrcService.js:551:25)
    at scope.linkTo (OnlineSrcDirective.js:2083:40)
    at fn (eval at compile (angular.js?v=293b1dbf3aae48af97080e26810e1eee152c7821:16548:15), <anonymous>:4:256)
    at callback (UtilityDirective.js:1831:24)
    at HTMLButtonElement.<anonymous> (UtilityDirective.js:1838:17)
    at HTMLButtonElement.dispatch (jquery-3.7.1.js?v=293b1dbf3aae48af97080e26810e1eee152c7821:5149:35)
    at elemData.handle (jquery-3.7.1.js?v=293b1dbf3aae48af97080e26810e1eee152c7821:4953:35)
```

Related to https://github.com/geonetwork/core-geonetwork/commit/307228062f0347fe45b7b42f24657631f7dfe0c5

* Update check to add service metadata layers as online resource

---------

Co-authored-by: François Prunayre <fx.prunayre@gmail.com>