API / Translation should never be null
When moving from older version, translations may be incomplete (depending on language setup changes). JSON can then contains null which make translate directive to fail with errors and it breaks the UI in some places:
```

TypeError: Cannot read property 'substr' of null
    at ha (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:390)
    at Function.V.instant (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:390)
    at c (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:390)
    at fn (eval at compile (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:237), <anonymous>:4:199)
    at lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:135
    at m.$digest (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:150)
    at m.$apply (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:154)
    at lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:166
    at e (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:57)
    at lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:60
```

The API op affected is:
http://localhost:8080/geonetwork/srv/api/0.1/tools/i18n/db?type=StatusValue&type=Operation&type=Group

Response causing issue is due to `null` value:
```
{
status-0: "Inconnu",
status-1: "Brouillon",
status-2: "Validé",
status-3: "Retiré",
status-4: "A valider",
status-5: "Rejeté",
group--1: null,
group-0: null,
group-1: "all",
```

Always set a default non empty value in the response.

From the catalog admin point of view, the complete fix in such case is to update the database missing translations.