[Backport 4.2.x] jQuery upgrade to version 3.7.1 (#8105)
* jQuery upgrade to version 3.7.1 (#8015)

* jQuery 3.7.1 upgrade

* Test to use jQuery 3.0.0

* Test to use jQuery 3.4.1

* Update to Jetty 10 - Update download distribution url

* Remove jQuery 2.2.4

* Update jQueryUI slider to 1.13.2

* HTML tags must be properly closed

* Disable jQuery migrate warnings

* HTML tags must be properly closed

* Update to boostrap-datepicker 1.10.0 to work with jQuery 3.7.1

* Update to bootstrap-datepicker 1.10.0 - add minified file and remove old css

* Disable jQueryMigrate self-closed-tags patch

Wrong self-closed html tags will cause the application to fail

* Update to bootstrap-datepicker 1.10.0 - Fix wro4j configuration

* Add missing bootstrap-datepicker3.css.map that caused a wro4j error. (#8078)

ERROR [geonetwork.wro4j] - Error occurred during a wro4j request handling
ro.isdc.wro.WroRuntimeException: Cannot build valid CacheKey from request: /geonetwork/static/bootstrap-datepicker3.css.map

* jQuery upgrade to version 3.7.1 - additional fixes