Editor / Init language autocomplete only on focus (#4409)
Some records define lots of languages (eg. 60 langs) then each field make a call to the service.

Depending on the setup, this can cause issue with the DB pool 
```
java.sql.SQLException: Cannot get a connection, pool error Timeout waiting for idle object
```

Symptom: part of the editor is not initialized properly eg. no keywords. Firefox seems to be more affected than Chrome.

Only init the autocomplete when the user focus on the field.