JS / Moment / Timezone lib missing when 3D mode enabled
Related to https://github.com/geonetwork/core-geonetwork/pull/4576

Error reported
```
TypeError: Cannot read properties of undefined (reading 'guess')
```