Fix ESAPI Logger configuration
ESAPI Logger configuration has changed in 2.2.1.0 (and later).

This fixes this error:
```
ESAPI: Attempting to load validation.properties via the classpath.
ESAPI: validation.properties could not be loaded by any means. fail..
 Caught java.lang.IllegalArgumentException;
  exception message was: java.lang.IllegalArgumentException: Failed to load ESAPI.properties as a classloader resource.
Error at xsl:value-of on line 52 of error.xsl:
  Exception in extension function org.owasp.esapi.errors.ConfigurationException:
  java.lang.ClassNotFoundException: org.owasp.esapi.reference.Log4JLogFactory LogFactory
  class (org.owasp.esapi.reference.Log4JLogFactory) must be in class path.
2022-05-17 17:36:18,578 ERROR [jeeves] - Exception in extension function
  org.owasp.esapi.errors.ConfigurationException: java.lang.ClassNotFoundException:
   org.owasp.esapi.reference.Log4JLogFactory LogFactory class (org.owasp.esapi.reference.Log4JLogFactory) must be in class path.
```

From the release notes:

However, if you try to juse the new ESAPI 2.2.1.0 or later logging you will notice that you need to change ESAPI.Logger and also possibly provide some other properties as well to get the logging behavior that you desire.

To use ESAPI logging in ESAPI 2.2.1.0 (and later), you will need to set the ESAPI.Logger property to

    org.owasp.esapi.logging.java.JavaLogFactory     - To use the new default, java.util.logging (JUL)
    org.owasp.esapi.logging.log4j.Log4JLogFactory   - To use the end-of-life Log4J 1.x logger
    org.owasp.esapi.logging.slf4j.Slf4JLogFactory   - To use the new (to release 2.2.0.0) SLF4J logger

In addition, if you wish to use JUL for logging, you *MUST* supply an "esapi-java-logging.properties" file in your classpath. This file is included in the 'esapi-2.2.2.0-configuration.jar' file provided under the 'Assets' section of the GitHub Release at
    https://github.com/ESAPI/esapi-java-legacy/releases/esapi-2.2.2.0