Harvester / ISO19115-3 / Better support missing metadata date info (#8414)
While harvesting, `extract-date-modified.xsl` is used to retrieve last update of the record. If empty, harvester will fail with:

```
[geonetwork.harvester] - Invalid ISO date: 
java.lang.IllegalArgumentException: Invalid ISO date: 
	at org.fao.geonet.domain.ISODate.parseDate(ISODate.java:426) ~[gn-domain-4.4.5-SNAPSHOT.jar:?]
	at org.fao.geonet.domain.ISODate.setDateAndTime(ISODate.java:239) ~[gn-domain-4.4.5-SNAPSHOT.jar:?]
	at org.fao.geonet.domain.ISODate.<init>(ISODate.java:117) ~[gn-domain-4.4.5-SNAPSHOT.jar:?]
	at org.fao.geonet.kernel.harvest.harvester.simpleurl.Aligner.addMetadata(Aligner.java:237) ~[gn-harvesters-4.4.5-SNAPSHOT.jar:?]
	at org.fao.geonet.kernel.harvest.harvester.simpleurl.Aligner.lambda$insertOrUpdate$0(Aligner.java:126) ~[gn-harvesters-4.4.5-SNAPSHOT.jar:?]
```


Fallback to now.

Co-authored-by: François Prunayre <fx.prunayre@gmail.com>