Avoid writing empty multipolygons to spatialindex. Otherwise postgres causes GeoNetwork to fail on restart with exception as follows:
org.postgresql.util.PSQLException: ERROR: geometry contains non-closed rings