Return application exception instead of JPA transaction errors when duplicated UUID is created.
eg. while running XSL processing and when a UUID which already exists is created
(that may happen when a schema define custom rule to build UUID in update-fixed-info)
a DataIntegrityViolationException is returned and stop the whole process:

```
Caused by: org.postgresql.util.PSQLException:
ERROR: duplicate key value violates unique constraint \"metadata_uuid_key\"\n
Détail : Key (uuid)=(SDN_CPRD_3471_BSBD) already exists.\n\tat
```

In order to have processing moving to the next record, run a check in DataManager
to avoid to throw the JPA at the transaction level but rather send a clear
message to user to indicate that the result of the process build an existing UUID:

```
 "metadataErrors": {
    "100470": [
      {
        "message": "Another record exist with UUID 'SDN_CPRD_3471_BSBD'. This record as internal id '334236472'. The record you're trying with id '100470' to update can not be saved.",
        "date": "2018-02-26T16:38:56",
        "stack": "java.lang.IllegalArgumentException: Another record exist with UUID 'SDN_CPRD_3471_BSBD'. This record as internal id '334236472'. The record you're trying with id '100470' to update can not be saved...
      }
    ],
```