JS & CSS / Cache / Add a profile to prebuilt the wro4j-cache (#6774)
* Adds a profile to prebuilt the wro4j-cache

Add the wro4j-prebuild-cache maven profile for building the WRO4J cache in
build time and use it when Geonetwork starts.
If the data directory doesn't contain a wro4j-cache database or the git version
stored in the data directory doesn't match the GeoNetwork's git commit hash then
copy the prebuilt cache to the data directory.
If copied the cache and GN has custom CSS & JS settings in the DB then delete
all the CSS items from the cache to allow the LESS compiler take it on runtime.

* Update oaipmh.js

```
SEVERE: file:/web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.js:24: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
              "validate": "NOVALIDATION",
                                        ^
```

* WRO4J / Build time / Add target groups to only build resources we are using.

* WRO4J / Log LESS errors as Warning.

* Replace wro4j-cache.mv.db on copy from prebuilt folder

* Autoclose streams using try-with-resources

* Remove code smells

* Remove unused import.
* Remove method to simply inherit it.
* Define and throw a dedicated exception instead of using a generic one.

* Remove unsused import

* WRO4J / Maven build cache / Fix template cache URL

Template cache was created using source code path:
```js
$templateCache.put('../../home/dev/src/geonetwork/src/geonetwork-val/web-ui/src/main/resources/sextant/components/common/map/print/partials/printmap.html'
```
instead of relative webapp path
```js
$templateCache.put('../../catalog/templates/editor/new-metadata-horizontal.html'
```

---------

Co-authored-by: François Prunayre <fx.prunayre@gmail.com>