AngularJs upgrade to version 1.8.2 (#6693)
* Upgrade AngularJs to version 1.8.3

* Update the default location provider hash-prefix '!' to empty string

* Code formatting

* Update  request

* Upgrade AngularJs to version 1.8.3 - update typeahead http request

* Upgrade AngularJs to version 1.8.3 - fix create metadata

* Upgrade AngularJs to version 1.8.3 - fix harvesters

* Upgrade AngularJs to version 1.8.3 - fix batch edit

* Upgrade AngularJs to version 1.8.3 - change angular.uppercase to use toUpperCase()

* Upgrade AngularJs to version 1.8.3 - fix new metadata error handler

* Upgrade AngularJs to version 1.8.3 - fix map layer opacity slider error:

Error: [ngModel:numfmt] Expected /tmp/core-geonetwork/web to be a number

* Upgrade AngularJs to version 1.8.3 - fix feature tables. (#64)

Co-authored-by: François Prunayre <fx.prunayre@gmail.com>