PDF / Report image URL in case of error
Provide some more context to user about the error


```
2023-04-26T12:37:21,072 ERROR [geonetwork] - Error writing metadata to PDF
java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088) ~[?:1.8.0_362]
	at org.fao.geonet.api.records.formatters.ImageReplacedElementFactory$UrlImageLoader.loadImage(ImageReplacedElementFactory.java:289) ~[classes/:?]
```

replaced by
```
2023-04-26T12:46:31,470 ERROR [geonetwork] - Error loading image /images/logos/c9c5a394-882a-4520-8011-7f6c11ffaa5a.png for PDF
java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088) ~[?:1.8.0_362]
```

Logging as warning as it is not blocking PDF creation.