Editor / Bounding polygon improvements.
* Preserve polygon input projection
* Fix empty namespace on non WGS84 geometries

```
org.jdom.IllegalAddException: The namespace xmlns="" could not be added as a namespace to "Polygon": The namespace prefix "" collides with the element namespace prefix
```

* Remove unecessary metadocument cleanup
* Editor / Bounding polygon / Read the data projection #2261
* Editor / Bounding polygon / Polygon is converted to WGS84 whatever is the initial projection #2262
* Add missing gml/@id for polygon and multisurface element.